### ISSUE TITLE
Pas d'affichage

### ISSUE THREAD

**Issue by Rodo5091** [Poups74/dentalalaniz#1]
J'ai bien tous les dossiers, par contre je n'arrive pas à l'afficher sur la page localhost

**Comment by Poups74** [comment]
je pense qu'iul va nous l'expliquer

**Comment by Poups74** [comment]
moi mon dossier n'est même pas ou tourne symfony donc ca ne risque pas de fonctionner

**Comment by Rodo5091** [comment]
résolu il faut installer 
1/composer install
2/npm install
3/npm run dev / npm run watch
