### ISSUE TITLE
Fichier Dentalaniz.code-workspace à ignorer

### ISSUE THREAD

**Issue by AymDev** [Poups74/dentalalaniz#3]
Un fichier de VS Code qui devrait être ignoré par Git a été envoyé sur votre dépôt: [ dentalalaniz/templates/Dentalaniz.code-workspace ](https://github.com/Poups74/dentalalaniz/blob/master/templates/Dentalaniz.code-workspace).

En ajoutant la ligne suivante à votre `.gitignore`, tous les fichiers avec l'extension `.code-workspace` devraient normalement être ignorés dans le futur:
```
**/*.code-workspace
```

**Comment by Rodo5091** [comment]
Pensez à bien supprimer l'extension .code-workspace

**Comment by AymDev** [comment]
Le problème avait été réglé mais est réapparu suite au [85055fa](https://github.com/Poups74/dentalalaniz/commit/85055fab1f04f334eeb7976c8a3bfbf6a3b98580#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947) de @Poups74 .
On a re-réglé le problème (cf [feb68d9](https://github.com/Poups74/dentalalaniz/commit/feb68d9bc0aacfc62345b3be8161c4d620f3b794#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947)), vous pourrez fermer ce ticket lorsque sa branche `Fixtures` aura été fusionnée dans `master`.
