### ISSUE TITLE
Controller et dossier de template "record" à renommer

### ISSUE THREAD

**Issue by AymDev** [Poups74/dentalalaniz#4]
Il y a un [`RecordController`](https://github.com/Poups74/dentalalaniz/blob/master/src/Controller/RecordController.php) et un dossier de template [`record`](https://github.com/Poups74/dentalalaniz/tree/master/templates/record) dans le projet.

Ce devrait être renommé, **record** provient du projet de cours (les *albums*) mais n'a rien à voir avec votre projet actuel.

**Comment by Rodo5091** [comment]
En effet il faut renommer RecordController, je l'ai aperçu chez seb
